"""add legacy_crypto flag to hosts

Revision ID: 69ee9a08e285
Revises: 742bf5e05b97
Create Date: 2026-07-05 16:48:30.799012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69ee9a08e285'
down_revision: Union[str, Sequence[str], None] = '742bf5e05b97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'hosts',
        sa.Column('legacy_crypto', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hosts', 'legacy_crypto')
    # ### end Alembic commands ###
